#!/usr/bin/env php
<?php
define('INFILE', __DIR__ . '/README.md-dist');
define('OUTFILE', '/vagrant/README.md');

function run($command) {
    $output = $status = '';
    exec($command, $output, $status);

    return trim(implode(PHP_EOL, $output));
}

$commands = array(
    'PHP (system default)' => 'php -v',
    'atoum' => 'atoum -v',
    'PHPMD' => 'phpmd --version',
    'PHP_Depend' => 'pdepend  --version',
    'PHP_CodeSniffer' => 'phpcs --version',
    'PhpSwitch' => 'phpswitch --version',
    'Phing' => 'phing -version',
    'PHPUnit' => 'phpunit --version'
);

$installed = '<table>' . PHP_EOL;
$installed .= '<thead><tr><th>Utility</th><th>Version</th></thead><tbody>' . PHP_EOL;

foreach($commands as $name => $command) {
    $output = run($command);
    $installed .= sprintf(
        '<tr><th>%s</th><td>%s</td></tr>' . PHP_EOL,
        $name,
        nl2br(run($command))
    );
}

$installed .= '</tbody></table>' . PHP_EOL;

$content = file_get_contents(INFILE);
$content = str_replace('%installed%', $installed, $content);

if(true === file_exists(OUTFILE)) {
    unlink(OUTFILE);
}
file_put_contents(OUTFILE, $content);
